name: test_reporter
description: CLI Utility to wrap dart tests with reporter plugins
version: 1.1.3
repository: https://github.com/rIIh/dart_test_reporter
issue_tracker: https://github.com/rIIh/dart_test_reporter/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+%5Btest_reporter%5D

environment:
  sdk: ^3.0.0

dependencies:
  path: ^1.8.0
  uuid: ^4.4.0
  freezed_annotation: ^2.4.1
  args: ^2.5.0
  universal_io: ^2.2.2
  ansicolor: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

  # codegen
  build_runner: ^2.4.11
  freezed: ^2.5.3
  json_serializable: ^6.8.0

executables:
  test_reporter:
