name: allure_report
description: Allure Report Adapter. Use it with [test_reporter](https://pub.dev/packages/test_reporter) package
version: 1.0.0
repository: https://github.com/rIIh/dart_test_reporter
issue_tracker: https://github.com/rIIh/dart_test_reporter/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+%5Ballure_report%5D

environment:
  sdk: ^3.4.1

dependencies:
  path: ^1.9.0
  freezed_annotation: ^2.4.1
  test_reporter: ^1.0.0
  universal_io: ^2.2.2
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.3
  lints: ^3.0.0
  test: ^1.24.0
