name: allure_server_cli
description: CLI tool for communication with [Allure Server](https://github.com/kochetkov-ma/allure-server)
version: 1.0.3
repository: https://github.com/rIIh/dart_test_reporter
issue_tracker: https://github.com/rIIh/dart_test_reporter/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+%5Ballure_server_cli%5D

environment:
  sdk: ^3.0.0
  
dependencies:
  args: ^2.5.0
  dio: ^5.4.3+1
  http_parser: ^4.0.2
  logger: ^2.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  allures: